TACT-162: Page twitches when calling an additional menu
tact-app/web pull request #323
Opened 2023-01-24 19:05 UTC by al-petrushin

**Describe the issue**

[TACT-162](https://linear.app/octolab/issue/TACT-162/page-twitches-when-calling-an-additional-menu)

**Describe the pull request**

Added a parent container for the menu portal. 
Looks like a hack and is a hack. 🧐
But it works and now the menu increases the parent container and accordingly the scrolling.

2023-01-25 06:00 UTC, kamilsk requested changes
I blocked it, need to think

2023-01-26 06:08 UTC, malakhovmisha commented on components/shared/TasksList/components/TaskItemMenu/index.tsx
> +  console.log('console.log(menuPortalRef)', menuPortalRef)
no console

2023-01-26 06:11 UTC, kamilsk commented
fixed in next pr #328

2023-01-26 06:11 UTC, closed without merging

2023-01-26 06:11 UTC, kamilsk commented
thanks for contribution!